### ISSUE TITLE
Predict won't work

### ISSUE THREAD

**Issue by IgorFlint** [deeplearninc/a2ml#12]
docker run with the latest worker image is never exits... it creates _predicted file and just hangs after that

**Comment by vlad-dplrn** [comment]
to reproduce do:
a2ml new some-project -s iris.csv -t species
cd some-project
a2ml import
a2ml train
a2ml evaluate
wait till search is done, a2ml evaluate will print leaderboard
select on of the model id-s from leaderboard and do
a2ml deploy <model-id> --locally
a2ml predict ../iris.csv -m <model-id>

**Comment by IgorFlint** [comment]
@vlad-dplrn, please close the issue if it's gone
