### ISSUE TITLE
allow automatic authentication from file referred to by env variable

### ISSUE THREAD

**Issue by soggytee** [deeplearninc/a2ml#18]
so env variable like "AUGER_CREDENTIALS"

which points to file which has credentials
AUGER.JSON would then have contents with user email and private key
AUTH step can be there but shouldnt be necessary

**Comment by vlad-dplrn** [comment]
Credentials lookup:
1. env AUGER_CREDENTIALS set with credentials json - in case there is no persistent filesystem, like heroku app
2. env AUGER_CREDENTIALS_PATH set with path to folder with credentials file auger.json
3. path_to_credentials is set in auger.yaml
4. use default $HOME/.augerai/auger.json
